package step2;

import java.util.ArrayList;
import java.util.List;

import static step2.Calculator.*;

public class LottoMain {
    public static final int LOTTO_PRICE = 1000;

    public void main(String[] args) {
        int lottoNum = InputView.buyLotto() / LOTTO_PRICE;
        ResultView.printLottoCount(lottoNum);

        List<Lotto> autoLottoLists = autoLottoLists(lottoNum);
        ResultView.printLottoNum(autoLottoLists);

        Lotto lastWinner = new Lotto(InputView.getLastWinner());
        List<Integer> results = Lotto.compareWithLastLotto(autoLottoLists, lastWinner);
        ResultView.printDrawResult(results);

        int revenue = calculateRevenue(results);
        ResultView.printPercentage(calculatePercentage(lottoNum * LOTTO_PRICE, revenue));
    }

    private List<Lotto> autoLottoLists(int lottoNum) {
        List<Lotto> lottoArray = new ArrayList<>(lottoNum);

        for (int i = 0; i < lottoNum; i++) {
            lottoArray.add(new Lotto(AutoGenerated.getLotto()));
        }
        return lottoArray;
    }
}
